name:                auth0-client
version:             0.1.0.0
github:              "dvekeman/auth0-client"
license:             BSD3
author:              "Dieter Vekeman"
maintainer:          "dieter.vekeman@gmail.com"
copyright:           "(c) Tinkhaven"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Auth0 API Client
category:            Web

description:         Please see the README on GitHub at <https://github.com/dvekeman/auth0-client#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- http-client
- http-client-tls
- servant
- servant-client
- text

library:
  source-dirs: src

tests:
  auth0-client-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - auth0-client
