name:                auth0-client
version:             0.1.0.0
github:              "dvekeman/auth0-client"
license:             BSD3
author:              "Dieter Vekeman"
maintainer:          "dieter.vekeman@gmail.com"
copyright:           "(c) Tinkhaven"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dvekeman/auth0-client#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  auth0-client-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - auth0-client

tests:
  auth0-client-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - auth0-client
